FROM node:12.18.3-alpine
RUN npm i -g nodemon
WORKDIR /code
COPY backend/package.json package.json
COPY backend/package-lock.json package-lock.json      
RUN npm install
COPY backend/server.js ./server
COPY backend/server .
ENTRYPOINT [ "nodemon","server.js"]